<a href="https://colab.research.google.com/github/ucfilho/optim_raianars_Insight/blob/master/DE_OPTIM_ANN_006_Insight.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
############################### Importar códigos

!git clone https://github.com/ucfilho/optim_raianars_Insight/ #clonar do Github

fatal: destination path 'optim_raianars_Insight' already exists and is not an empty directory.


In [2]:
%cd optim_raianars_Insight
#!ls

/content/optim_raianars_Insight


In [0]:
def AvaliaX(X):
  nrow,ncol=X.shape
  fitness = np.asarray([Fun(ind) for ind in X])
  best_idx = np.argmin(fitness)
  best = X[best_idx]
  fobj_best = fitness[best_idx]
  y=fitness
  BEST=best
  FOBEST=fobj_best
  XY= np.c_[X,y] #concatena x e y em 2 colunas            
  XYsorted = XY[XY[:,-1].argsort()] #Ordena a partir da last col(Y) for all row
  x=XYsorted[:,0:ncol]
  XY=XYsorted
  BEST_XY =np.append(BEST,FOBEST)
  return XY,BEST_XY,BEST,FOBEST

In [0]:
############################### Importar bibliotecas e iniciar a contagem do tempo
import time
import matplotlib.pyplot as plt
import numpy as np
from random import randint
from scipy import optimize
import de_bounds_matriz
import de_soma_Insight
import pandas as pd
###############################

In [0]:
############################### DADOS DE ENTRADA 
RUNS=1 #NÚMERO DE RODADAS
#mut=0.8
#crossp=0.7
  ############################### Função
import Function

'''
Fun=Function.Rosenbrock
dim=30
MAX=np.repeat(10,dim)
MIN=np.repeat(-10,dim)

  #Global optimum: f(xi)= 0
'''
'''
dim=30
Fun=Function.Sphere
MAX=np.repeat(5.12,dim)
MIN=np.repeat(-5.12,dim)
  # f(x)=0 x=(0,0) [-5.12,5.12]
'''
#'''
dim=2
Fun=Function.Schwefel
MAX=np.repeat(500,dim)
MIN=np.repeat(-500,dim)
  #Global optimum: f(xi)= 0 for xi = 420.968746 for i=1,...,n  ;  xi in [-500,500]  
#'''
'''
dim=30
Fun=Function.Rastrigin
MAX=np.repeat(5.12,dim)
MIN=np.repeat(-5.12,dim)
  # f(x)=0 x=(0,0) [-5.12,5.12]
'''
'''
dim=30
Fun=Function.Sum_of_different_powers
MAX=np.repeat(1,dim)
MIN=np.repeat(-1,dim)
  # f(x)=0 x=(0,0)
'''
'''  
dim=30
Fun=Function.Ackley
MAX=np.repeat(32,dim)
MIN=np.repeat(-32,dim)
 # f(x)=0 x=(0,0) [-32, 32]
'''
'''  
dim=30
Fun=Function.Michalewicz
MAX=np.repeat(np.pi,dim)
MIN=np.repeat(0,dim)
 #fx=-9.66015 p/ d=10 [0,pi]
'''
'''  
dim=30
Fun=Function.
MAX=np.repeat(1,dim)
MIN=np.repeat(-1,dim)
'''

PAR=len(MAX) #NUM DE PARAMETROS A SER OTIMIZADOS


In [0]:
def GeraIndices(X,BESTo,FOBESTo,DIo,MAT_INDo,SOMA,TOTAL):
  
  nrow,ncol=X.shape
  FOBESTm=1e99
  Fo=MAT_INDo[0,6]    # VALOR Fo   
  CRo=MAT_INDo[0,7]   # VALOR CRo
  #print("========inicio===========");print(MAT_INDo[0,[6,7,15,16]])
  QUANT=17 # quantos indices esta fazendo
  #MAT_IND=np.copy(MAT_INDo)
  MAT_IND=np.zeros((1,QUANT))

  REF=0.1 # REFERENCIA DE DIFERENCAS ENTRE OS ELEMENTOS
  
  XY,BEST_XY,BEST,FOBEST=AvaliaX(X)
  soma=0
  for j in range(ncol):
    for i in range(nrow):
        Xj=np.mean(X[:,j])
        soma=soma+(X[i,j]-Xj)**2
  DI=(soma/nrow)**0.5
  DIr=DI/DIo
  MAT_IND[0,0]=DI #dispersao
  MAT_IND[0,1]=DIr # dispersao relativa
  MAT_IND[0,2]=SOMA/TOTAL # fracao relativa
  # MAT_IND[0,3] velocidade relativa
  V1=FOBESTo
  V2=FOBEST
  A=2*V2
  if(V1 > A):
    MAT_IND[0,3]=2 # o valor de fobj torna pelo menos duas vezes melhor
  elif (V2==V1):
    MAT_IND[0,3]=0 # o valor de fobj nao altera
  else:
    MAT_IND[0,3]=1 # o valor de fobj melhora mas menos que duas vezes
  
  # MAT_IND[0,4]  # VELOC X
  DELTA=np.amax(abs(BEST-BESTo))
  if( DELTA >REF):
    MAT_IND[0,4]=2 # difere  for i in range(1,len(PARTIC)):
  elif ( DELTA == 0):
    MAT_IND[0,4]=0 # sem diferenca entre as posicoes do xbest entre duas buscas
  else:
    MAT_IND[0,4]=1 # diferenca entre as posicoes  do xbest menor que ref
  
  MAT_IND[0,5]=nrow  # VALOR NP
  #MAT_IND[0,6]=MAT_INDo[0,15]
  #MAT_IND[0,7]=MAT_INDo[0,16]


  nrow,ncol=XY.shape
  MAT_IND[0,8]=XY[0,(ncol-1)] # VALOR fmin
  MAT_IND[0,9]=XY[(nrow-1),(ncol-1)] # VALOR fmax
  # MAT_IND[0,10] # Valor AD_fmin 
  if abs(MAT_IND[0,8]/MAT_IND[0,8])>1:
    MAT_IND[0,10]=1/abs(MAT_IND[0,8])
  else:
    MAT_IND[0,10]=MAT_IND[0,8]/MAT_IND[0,8]
  # MAT_IND[0,11] # Valor AD_fmax
  if abs(MAT_IND[0,9]/MAT_IND[0,9])>1: # tem que pegar primeira
    MAT_IND[0,11]=1/abs(MAT_IND[0,9]) # tem que pegar primeira
  else:
    MAT_IND[0,11]=MAT_IND[0,9]/MAT_IND[0,9] # tem que pegar do anterior

  # MAT_IND[0,12] # DELTA Fobj
  MAT_IND[0,12]=MAT_IND[0,3]-MAT_IND[0,3]  # tem que pegar do anterior
  

  # MAT_IND[0,13] # DELTA Vx
  MAT_IND[0,13]=MAT_IND[0,4]-MAT_IND[0,4]  # tem que pegar do anterior

  # MAT_IND[0,14] # r_fitness
  Fmin=0.05
  if (MAT_IND[0,8]==0):
    MAT_IND[0,14]=Fmin
  elif (MAT_IND[0,9]==0):
    MAT_IND[0,14]=Fmin
  else:
    if abs(MAT_IND[0,9]/MAT_IND[0,8])<1:
      MAT_IND[0,14]=1-abs(MAT_IND[0,9]/MAT_IND[0,8])
    else:
      MAT_IND[0,14]=1-abs(MAT_IND[0,8]/MAT_IND[0,9])

  MAT_IND[0,6]=Fo
  MAT_IND[0,7]=CRo

  Fo=Fo+0.5
  CRo=CRo+2
  
  
  MAT_IND[0,15]=Fo # valor de F que sai da rede
  MAT_IND[0,16]=CRo # valor de CR que sai da rede

  print("=======final==========");print(MAT_IND[0,[6,7,15,16]])
  
  return MAT_IND



In [7]:
##################################### IMPORTAR MÓDULOS

NMAX=1000 # maximo tamanho da populacao

dimensions=len(MAX)

start_time = time.time() #INICIALIZA CONTAGEM DO TEMPO
its=1 # quantas vezes vai usar o NPAR antes de alterar de novo
ITE=6 # PONTOS quantas vezes vai alteral NPAR 
#PARTIC=[10,80,10,400,100,100,100,100,100,100]
#ITE=50 # so para testar

#TOTAL=7*dim*its*ITE
TOTAL=10*dim*its*ITE

maxiter=3
popsize=5
p=int(TOTAL/its/ITE) 
NPAR=p

MAX_P=np.zeros(ITE) # ATENCAO para variar F e Cr MAX_P passa a ser 3 vezes maior
MIN_P=np.zeros(ITE) # ATENCAO para variar F e Cr  MIN_P passa a ser 3 vezes maior

for i in range(dim):
  MAX_P[i]=MAX[i] 
  MIN_P[i]=MIN[i]


for i in range(RUNS):
  SOMA=0
  pop = np.random.rand(NPAR, dimensions)
  diff=np.zeros(PAR)
  for ii in range(PAR):
    diff[ii] = MAX[ii]-MIN[ii]
  X = MIN + pop * diff
    
  PONTOS=ITE # DIVISOES DA POPULACAO
 
 ############################################################
  #bounds=[(5*dim, 15*dim)] * PONTOS # ITE
  #bounds=[(3*dim, 12*dim)] * PONTOS # ITE
  #bounds=[(4*dim, 16*dim)] * PONTOS
  
  # nao pode ser assim pq o bounds vale p o DE nao dos parametros
  #p=int(TOTAL/its/ITE) 
  bounds=[(p, p)] * PONTOS
  #bounds=[]
  #for k in range(dim):
  #  bounds.append((MIN[k], MAX[k]))
  # print("=========bounds=",bounds)
    


  '''
  #Geral
  new_mut=(0,1)
  new_crossp=(0,1)
  '''
  #'''
  #Multimodal Separável 
  new_mut=(0.5,1)
  new_crossp=(0,0.5)
  #'''
  '''
  #Multimodal Não Separável 
  new_mut=(0.5,1)
  new_crossp=(0.5,1)
  '''
  '''
  ##### Unimodal Separável
  new_mut=(0,0.5)
  new_crossp=(0,0.5)
  '''
  '''
  ##### Unimodal Não Separável
  new_mut=(0,0.5)
  new_crossp=(0.5,1)
  '''
 ############################################################ 
  # nao pode ser assim pq o bounds vale p o DE nao dos parametros
  ''' '''
  for j in range(PONTOS):
    bounds.append(new_mut)
    
  for j in range(PONTOS):
    bounds.append(new_crossp)

  DIo=1e99
  mut=0.5;crossp=0.5;
  CRo=crossp;Fo=mut;
  #Xo=np.copy(X)
  XY,BEST_XY,BESTo,FOBESTo=AvaliaX(X)
  nrow,ncol=X.shape

  QUANT=17;MAT_INDo=np.zeros((1,QUANT)); # quantos indices esta fazendo
  MAT_INDo[0,5]=nrow  # VALOR NP
  MAT_INDo[0,6]=Fo    # VALOR Fo   
  MAT_INDo[0,7]=CRo   # VALOR CRo
  
  

  
  MAT_INDo=GeraIndices(X,BESTo,FOBESTo,DIo,MAT_INDo,SOMA,TOTAL)
  
  DIo=np.copy(MAT_INDo[0,0])
  pd.set_option('display.max_columns', 30)  
  MAT_INDo[0,15]=Fo    # VALOR Fo   
  MAT_INDo[0,16]=CRo   # VALOR CRo
  MAT=[]
  for loop in range(ITE):
    X,BEST,FOBEST,XY,BEST_XY,SOMA= de_soma_Insight.de(MAX,MIN, mut, crossp,
                                                      NPAR, its,Fun,X,SOMA,TOTAL)
    
    MAT_IND=GeraIndices(X,BESTo,FOBESTo,DIo,MAT_INDo,SOMA,TOTAL)
    
    BESTo=np.copy(BEST);FOBESTo=np.copy(FOBEST);
    MAT.append(MAT_IND.ravel())
    
    MAT_INDo[0,6]=MAT_IND[0,15]   # VALOR Fo   
    MAT_INDo[0,7]=MAT_IND[0,16]   # VALOR CRo
    
NOMES=['DIVERSIDADE (DI)',  'DI RELATIVO','FRAC Its',
           'VELOC FOBJ','VELOC X','NP','Fo','CRo','fmin','fmax',
           'AD_fmin','AD_fmax','DELTA FOBJ','DELTA VX','r_fitness',
           'F','CR']
df  = pd.DataFrame(MAT, columns=NOMES)
pd.set_option('display.max_columns', 30)
pd.set_option('display.max_rows', 30)
print(df)

=======final==========
[0.5 0.5 1.  2.5]
=======final==========
[0.5 0.5 1.  2.5]
=======final==========
[1.  2.5 1.5 4.5]
=======final==========
[1.5 4.5 2.  6.5]
=======final==========
[2.  6.5 2.5 8.5]
=======final==========
[ 2.5  8.5  3.  10.5]
=======final==========
[ 3.  10.5  3.5 12.5]
   DIVERSIDADE (DI)  DI RELATIVO  FRAC Its  VELOC FOBJ  VELOC X    NP   Fo  \
0        394.695013     1.051655  0.166667         2.0      2.0  20.0  0.5   
1        334.398348     0.890996  0.333333         0.0      0.0  20.0  1.0   
2        346.176330     0.922378  0.500000         0.0      0.0  20.0  1.5   
3        325.635961     0.867649  0.666667         0.0      0.0  20.0  2.0   
4        350.600988     0.934168  0.833333         0.0      0.0  20.0  2.5   
5        332.010117     0.884633  1.000000         0.0      0.0  20.0  3.0   

    CRo      fmin         fmax  AD_fmin  AD_fmax  DELTA FOBJ  DELTA VX  \
0   0.5  57.36872  1218.620459      1.0      1.0         0.0       0.0   
1   2.5  5

In [8]:
print(Fo)

0.5
